version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: ./entrypoint.sh
    depends_on:
      - db
      - celery
      - redis
    environment:
      POSTGRES_HOST: db
    volumes:
      - ./smena/:/backend/smena
    ports:
      - "8000:8000"
    container_name: smena_web
  redis:
    image: redis:alpine
  db:
    image: postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: pg_isready -U postgres
      timeout: 20s
      retries: 3
    container_name: smena_db
    volumes:
      - db-data:/var/lib/postgresql/data

  celery:
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: celery --app core.celery_app  worker -l info
    environment:
      POSTGRES_HOST: db
    volumes:
      - ./smena:/backend/smena
    depends_on:
      - redis
      - db

volumes:
  db-data:
