# Generated by Django 4.0.4 on 2022-05-11 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('api_key', models.CharField(max_length=255)),
                ('check_type', models.CharField(choices=[('kt', 'Kitchen'), ('cl', 'Client')], max_length=2)),
                ('point_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('kt', 'Kitchen'), ('cl', 'Client')], max_length=2)),
                ('order', models.JSONField()),
                ('status', models.IntegerField(choices=[(1, 'new'), (2, 'rendered'), (3, 'printed')])),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checks.printer')),
            ],
        ),
    ]
