# Generated by Django 4.0.4 on 2022-05-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='order_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
