# Generated by Django 4.0.4 on 2022-05-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0002_check_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
